### PR TITLE
Making compound Features out of input Features

### PR DESCRIPTION
**Pull request by vishal1383**
Thank you for your contribution. Please provide the details requested below.

## ISSUE NUMBER

https://github.com/prateekiiest/titanic_survival_exploration/issues/9

## SHORT DESCRIPTION
I have made a compound feature inspired from Kaggle contestants Sinai,Anisotropic  who also make use of the Name feature from which they extract out title using Regular Expression matching.Title also contains the Information of Sex and some more extra information also.
## TESTING
Can run the code on a jupyter notebook.

### CODE REVIEW

**Review by imVivekGupta — COMMENTED** [review]
Interesting analysis. A couple of things which I noted:
1.
'train['Title'] = train['Title'].replace('Mlle', 'Miss')
train['Title'] = train['Title'].replace('Ms', 'Miss')
train['Title'] = train['Title'].replace('Mme', 'Mrs')'

This is done twice.

2. How did you get the Title feature in the csv file? We shouldn't modify the given input file explicitly. It would be better if you add the column in the dataframe in the code.

3. A few spelling errors in comments like 'corellation' and 'coloumn'

**Comment by vishal1383** [comment]
Will check and fix that as well Thanks
1.Actually, I added the code to obtain the histogram and forgot to delete after that .Thanks for pointing out.
2.I added the column Title in the data frame in the input on my local machine.Will modify it in the code to add a new column and correlation
3.My bad will fix that too.
Thanks !! for pointing out.

**Review by imVivekGupta — COMMENTED** [review]
The notebook is not view-able. It says invalid json object. Please check. There is some error here :

`Error: Parse error on line 215:
...rt pandas as pd\n",<<<<<<< HEAD    "tr
----------------------^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined '`

**Comment by vishal1383** [comment]
This shouldn't happen .Checking...

**Comment by vishal1383** [comment]
Have to make those changes again I guess..

**Review by imVivekGupta — APPROVED** [review]
Looks good now! :+1: Good work.

**Comment by vishal1383** [comment]
Thanks, will add the Pearson Correlation matrix and the accuracy obtained using the Title Feature also.

**Review by prateekiiest — APPROVED** [review]
Thanks for the contribution @vishal1383

**Comment by prateekiiest** [comment]
And @imVivekGupta , thanks for the helping hand :)

**Pull request merged**
