### PR TITLE
Added Embarked_Vs_Survived Plot And Engineered Features

### PR DESCRIPTION
**Pull request by shreyas-kowshik**
## SHORT DESCRIPTION
Added the Embarked_Vs_Survived plots for visualizations.

## TESTING
Run the python code and get the required plot.

### CODE REVIEW

**Comment by shreyas-kowshik** [comment]
@prateekiiest please review

**Comment by shreyas-kowshik** [comment]
Please review @prateekiiest

**Comment by prateekiiest** [comment]
there some issues with codacy and codeclimate, please fix them

**Comment by prateekiiest** [comment]
Tests are failing.

**Comment by shreyas-kowshik** [comment]
As in for the code quality?

**Comment by shreyas-kowshik** [comment]
Checked and reviewed the engineered_features.py file for errors and updated the code accordingly @prateekiiest .

**Comment by prateekiiest** [comment]
there are still some failing issues @shreyas-kowshik

**Comment by shreyas-kowshik** [comment]
can you please elaborate?The code compiles fine on my side and produces the proper output.Is there an issue with the code quality?If yes then in one implementation I cannot reduce the nesting and the logic for it is quite simple,so complexity is not much logically speaking.The quality has issues there only mainly.
@prateekiiest

**Comment by prateekiiest** [comment]
its actually the code style that codacy/ codeclimate hints at.

If you use too much loops it will make it worse.
Instead of loops you should go for some thing like `np.iterate` or other that are vectorized

**Comment by prateekiiest** [comment]
still failing

**Comment by prateekiiest** [comment]
would you wanna work on this ?

**Comment by prateekiiest** [comment]
I am closing this as of now

**Comment by prateekiiest** [comment]
I will work on your code and will merge it later :smile:

**Pull request closed without merging**
