### PR TITLE
Adding Pclass plots

### PR DESCRIPTION
**Pull request by imVivekGupta**
## ISSUE NUMBER
#12 
## SHORT DESCRIPTION
Continuation of Visualization plots for accuracy based on individual features
## TESTING
Move to Illustrations/Pclass/ and run `python pclass_accuracy.py`

### CODE REVIEW

**Comment by imVivekGupta** [comment]
The failed check refers to duplicate code in two **separate** files.

**Comment by prateekiiest** [comment]
may be in some files the same implementation is already being done

**Comment by prateekiiest** [comment]
I am merging this

**Comment by prateekiiest** [comment]
Thanks @imVivekGupta

**Pull request merged**
